// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.220
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Nav.Common.VSPackages.VSFormatFile
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GuidVSFormatFilePkgString = "253b8a4d-86e4-4f76-b754-17675f3aa32f";
        public const string GuidVSFormatFileOptionsString = "20b21087-c0c6-4d62-a51c-4ac472825712";
        public const string GuidVSFormatFileOutputWindowPaneString = "6837c8a8-b325-4f1b-8fc6-8108e0a648ce";
        public const string guid1String = "64da400e-b4ad-4d67-aa92-4b7acb01ecd5";
        public const string guid2String = "78f03954-2fb8-4087-8ce7-59d71710b3bb";
        public const string guid3String = "4c87b692-1202-46aa-b64c-ef01faec53da";
        public const string guidJsonString = "f718ca06-cf4f-4a0c-9106-e79e9ee5e7cd";
        public const string GuidVSFormatFileCmdSetCodeString = "639e6837-1c8f-4261-b50e-f2d7ad6dca5b";
        public const string GuidVSFormatFileCmdSetFileString = "d0852ddf-b3b7-48c7-aed0-3bbbb776dc0f";
        public const string GuidVSFormatFileCmdSetFolderString = "15c4338e-cf6f-4e42-8de9-cd676682d53d";
        public const string GuidVSFormatFileCmdSetProjectString = "aa39165f-5dcd-4707-be3b-05e3a554cf9d";
        public const string GuidVSFormatFileCmdSetSolutionString = "cdc5a349-66bf-4541-ab4c-b540a8d72907";
        public static Guid GuidVSFormatFilePkg = new Guid(GuidVSFormatFilePkgString);
        public static Guid GuidVSFormatFileOptions = new Guid(GuidVSFormatFileOptionsString);
        public static Guid GuidVSFormatFileOutputWindowPane = new Guid(GuidVSFormatFileOutputWindowPaneString);
        public static Guid guid1 = new Guid(guid1String);
        public static Guid guid2 = new Guid(guid2String);
        public static Guid guid3 = new Guid(guid3String);
        public static Guid guidJson = new Guid(guidJsonString);
        public static Guid GuidVSFormatFileCmdSetCode = new Guid(GuidVSFormatFileCmdSetCodeString);
        public static Guid GuidVSFormatFileCmdSetFile = new Guid(GuidVSFormatFileCmdSetFileString);
        public static Guid GuidVSFormatFileCmdSetFolder = new Guid(GuidVSFormatFileCmdSetFolderString);
        public static Guid GuidVSFormatFileCmdSetProject = new Guid(GuidVSFormatFileCmdSetProjectString);
        public static Guid GuidVSFormatFileCmdSetSolution = new Guid(GuidVSFormatFileCmdSetSolutionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int guid1sym1 = 0x0002;
        public const int guid2sym1 = 0x0001;
        public const int guid3sym1 = 0x0103;
        public const int guidJson_ContextMenu = 0x0003;
        public const int MenuGroupCode = 0x1020;
        public const int CmdIdVSFormatFileCode = 0x0100;
        public const int CmdIdVSFormatFileOpenDocuments = 0x0101;
        public const int CmdIdJSBeautifierOnSaveCode = 0x0102;
        public const int CmdIdJSBeautifierOnSaveOpenDocuments = 0x0103;
        public const int MenuGroupFile = 0x1020;
        public const int CmdIdVSFormatFileFile = 0x0101;
        public const int CmdIdJSBeautifierOnSaveFile = 0x0102;
        public const int MenuGroupFolder = 0x1020;
        public const int CmdIdVSFormatFileFolder = 0x0102;
        public const int CmdIdJSBeautifierOnSaveFolder = 0x0103;
        public const int MenuGroupProject = 0x1020;
        public const int CmdIdVSFormatFileProject = 0x0103;
        public const int CmdIdJSBeautifierOnSaveProject = 0x0104;
        public const int MenuGroupSolution = 0x1020;
        public const int MenuGroupSolutionFolder = 0x1021;
        public const int CmdIdVSFormatFileSolution = 0x0104;
        public const int CmdIdVSFormatFileSolutionFolder = 0x0105;
        public const int CmdIdJSBeautifierOnSaveSolution = 0x0106;
        public const int CmdIdJSBeautifierOnSaveSolutionFolder = 0x0107;
    }
}
